CREATE TABLE IF NOT EXISTS PUBLIC.user
(
  id       INTEGER PRIMARY KEY AUTO_INCREMENT,
  login    VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "user_login_uindex"
  ON PUBLIC.user (login);